// Code generated by counterfeiter. DO NOT EDIT.
package beerapifakes

import (
	"context"
	"sync"

	v1 "github.com/jkarlos000/technical-challenge/currency/api/proto/v1"
)

type FakeCurrencyServer struct {
	v1.UnimplementedCurrencyServer
	GetPriceStub        func(context.Context, *v1.Request) (*v1.Response, error)
	getPriceMutex       sync.RWMutex
	getPriceArgsForCall []struct {
		arg1 context.Context
		arg2 *v1.Request
	}
	getPriceReturns struct {
		result1 *v1.Response
		result2 error
	}
	getPriceReturnsOnCall map[int]struct {
		result1 *v1.Response
		result2 error
	}
	GetPriceStreamStub        func(*v1.Request, v1.Currency_GetPriceStreamServer) error
	getPriceStreamMutex       sync.RWMutex
	getPriceStreamArgsForCall []struct {
		arg1 *v1.Request
		arg2 v1.Currency_GetPriceStreamServer
	}
	getPriceStreamReturns struct {
		result1 error
	}
	getPriceStreamReturnsOnCall map[int]struct {
		result1 error
	}
	mustEmbedUnimplementedCurrencyServerStub        func()
	mustEmbedUnimplementedCurrencyServerMutex       sync.RWMutex
	mustEmbedUnimplementedCurrencyServerArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCurrencyServer) GetPrice(arg1 context.Context, arg2 *v1.Request) (*v1.Response, error) {
	fake.getPriceMutex.Lock()
	ret, specificReturn := fake.getPriceReturnsOnCall[len(fake.getPriceArgsForCall)]
	fake.getPriceArgsForCall = append(fake.getPriceArgsForCall, struct {
		arg1 context.Context
		arg2 *v1.Request
	}{arg1, arg2})
	stub := fake.GetPriceStub
	fakeReturns := fake.getPriceReturns
	fake.recordInvocation("GetPrice", []interface{}{arg1, arg2})
	fake.getPriceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCurrencyServer) GetPriceCallCount() int {
	fake.getPriceMutex.RLock()
	defer fake.getPriceMutex.RUnlock()
	return len(fake.getPriceArgsForCall)
}

func (fake *FakeCurrencyServer) GetPriceCalls(stub func(context.Context, *v1.Request) (*v1.Response, error)) {
	fake.getPriceMutex.Lock()
	defer fake.getPriceMutex.Unlock()
	fake.GetPriceStub = stub
}

func (fake *FakeCurrencyServer) GetPriceArgsForCall(i int) (context.Context, *v1.Request) {
	fake.getPriceMutex.RLock()
	defer fake.getPriceMutex.RUnlock()
	argsForCall := fake.getPriceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCurrencyServer) GetPriceReturns(result1 *v1.Response, result2 error) {
	fake.getPriceMutex.Lock()
	defer fake.getPriceMutex.Unlock()
	fake.GetPriceStub = nil
	fake.getPriceReturns = struct {
		result1 *v1.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeCurrencyServer) GetPriceReturnsOnCall(i int, result1 *v1.Response, result2 error) {
	fake.getPriceMutex.Lock()
	defer fake.getPriceMutex.Unlock()
	fake.GetPriceStub = nil
	if fake.getPriceReturnsOnCall == nil {
		fake.getPriceReturnsOnCall = make(map[int]struct {
			result1 *v1.Response
			result2 error
		})
	}
	fake.getPriceReturnsOnCall[i] = struct {
		result1 *v1.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeCurrencyServer) GetPriceStream(arg1 *v1.Request, arg2 v1.Currency_GetPriceStreamServer) error {
	fake.getPriceStreamMutex.Lock()
	ret, specificReturn := fake.getPriceStreamReturnsOnCall[len(fake.getPriceStreamArgsForCall)]
	fake.getPriceStreamArgsForCall = append(fake.getPriceStreamArgsForCall, struct {
		arg1 *v1.Request
		arg2 v1.Currency_GetPriceStreamServer
	}{arg1, arg2})
	stub := fake.GetPriceStreamStub
	fakeReturns := fake.getPriceStreamReturns
	fake.recordInvocation("GetPriceStream", []interface{}{arg1, arg2})
	fake.getPriceStreamMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCurrencyServer) GetPriceStreamCallCount() int {
	fake.getPriceStreamMutex.RLock()
	defer fake.getPriceStreamMutex.RUnlock()
	return len(fake.getPriceStreamArgsForCall)
}

func (fake *FakeCurrencyServer) GetPriceStreamCalls(stub func(*v1.Request, v1.Currency_GetPriceStreamServer) error) {
	fake.getPriceStreamMutex.Lock()
	defer fake.getPriceStreamMutex.Unlock()
	fake.GetPriceStreamStub = stub
}

func (fake *FakeCurrencyServer) GetPriceStreamArgsForCall(i int) (*v1.Request, v1.Currency_GetPriceStreamServer) {
	fake.getPriceStreamMutex.RLock()
	defer fake.getPriceStreamMutex.RUnlock()
	argsForCall := fake.getPriceStreamArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCurrencyServer) GetPriceStreamReturns(result1 error) {
	fake.getPriceStreamMutex.Lock()
	defer fake.getPriceStreamMutex.Unlock()
	fake.GetPriceStreamStub = nil
	fake.getPriceStreamReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCurrencyServer) GetPriceStreamReturnsOnCall(i int, result1 error) {
	fake.getPriceStreamMutex.Lock()
	defer fake.getPriceStreamMutex.Unlock()
	fake.GetPriceStreamStub = nil
	if fake.getPriceStreamReturnsOnCall == nil {
		fake.getPriceStreamReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getPriceStreamReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCurrencyServer) mustEmbedUnimplementedCurrencyServer() {
	fake.mustEmbedUnimplementedCurrencyServerMutex.Lock()
	fake.mustEmbedUnimplementedCurrencyServerArgsForCall = append(fake.mustEmbedUnimplementedCurrencyServerArgsForCall, struct {
	}{})
	stub := fake.mustEmbedUnimplementedCurrencyServerStub
	fake.recordInvocation("mustEmbedUnimplementedCurrencyServer", []interface{}{})
	fake.mustEmbedUnimplementedCurrencyServerMutex.Unlock()
	if stub != nil {
		fake.mustEmbedUnimplementedCurrencyServerStub()
	}
}

func (fake *FakeCurrencyServer) MustEmbedUnimplementedCurrencyServerCallCount() int {
	fake.mustEmbedUnimplementedCurrencyServerMutex.RLock()
	defer fake.mustEmbedUnimplementedCurrencyServerMutex.RUnlock()
	return len(fake.mustEmbedUnimplementedCurrencyServerArgsForCall)
}

func (fake *FakeCurrencyServer) MustEmbedUnimplementedCurrencyServerCalls(stub func()) {
	fake.mustEmbedUnimplementedCurrencyServerMutex.Lock()
	defer fake.mustEmbedUnimplementedCurrencyServerMutex.Unlock()
	fake.mustEmbedUnimplementedCurrencyServerStub = stub
}

func (fake *FakeCurrencyServer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getPriceMutex.RLock()
	defer fake.getPriceMutex.RUnlock()
	fake.getPriceStreamMutex.RLock()
	defer fake.getPriceStreamMutex.RUnlock()
	fake.mustEmbedUnimplementedCurrencyServerMutex.RLock()
	defer fake.mustEmbedUnimplementedCurrencyServerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCurrencyServer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v1.CurrencyServer = new(FakeCurrencyServer)
