dsn: "postgres://postgres-currency:54321/currency?sslmode=disable&user=postgres&password=postgres"
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
migration_url: "file://migrations"
server_port: 9091
currencylayer_api_key: ""