dsn: "postgres://127.0.0.1:54321/currency?sslmode=disable&user=postgres&password=postgres"
currencylayer_api_key: ""
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
migration_url: "file://migrations"
server_port: 9091
